<?php
declare(strict_types=1);

/**
 * Where this copy of the site is installed, as a URL path ending in "/".
 *
 * "/" from a document root, "/peachq/" when installed in a subdirectory of
 * another site. Emitted as <base> so relative URLs resolve against the install
 * root rather than the requested path -- which is what weberror.php needs,
 * since it is served for arbitrary URLs at arbitrary depth.
 *
 * Taken from SCRIPT_NAME, the URL path of the running script, rather than from
 * this file's location on disk. Both work for a real directory; only this one
 * works when the directory is a symlink to another site's document root, since
 * __DIR__ resolves to the link target and so is not under DOCUMENT_ROOT at all.
 */
function peachq_install_path(): string {
    $script = (string)($_SERVER['SCRIPT_NAME'] ?? '');
    if ($script === '' || $script[0] !== '/') {
        return '/';
    }
    $dir = str_replace('\\', '/', dirname($script));
    return rtrim($dir, '/') . '/';
}

/**
 * This page's address on peachq.org, for rel=canonical.
 *
 * Always peachq.org, even when served from peachq.org: a self-referencing
 * canonical is the recommended form, and one rule then covers this site and the
 * timestored.com/peachq mirror without checking which is running.
 */
function peachq_canonical_url(): string {
    $path = (string)parse_url((string)($_SERVER['REQUEST_URI'] ?? '/'), PHP_URL_PATH);
    $install = peachq_install_path();
    if ($install !== '/' && strpos($path, $install) === 0) {
        $path = substr($path, strlen($install));
    }
    return 'https://peachq.org/' . ltrim($path, '/');
}

function peachq_page_start(string $title, string $description = '', string $active = ''): void {
    $title = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
    $description = htmlspecialchars($description, ENT_QUOTES, 'UTF-8');
    $active = htmlspecialchars($active, ENT_QUOTES, 'UTF-8');
    // URLs are relative, not root-relative, so the whole site can be served
    // from a subdirectory as well as from the root -- see the note in
    // static/.htaccess. Every page using this template is served at depth 0
    // ("/repl", never "/a/repl"), so a bare "repl" resolves correctly in both.
    $nav = [
        'repl' => ['Try Live', 'repl'],
        'download' => ['Download', 'download'],
        'compatibility' => ['Compatibility', 'compatibility'],
        'roadmap' => ['Roadmap', 'roadmap'],
        // news is MkDocs output, so it needs the trailing slash that directory
        // URLs use. It never matches $active, since those pages are generated by
        // Material rather than rendered through this template.
        'news' => ['News', 'news/'],
        'about' => ['About', 'about'],
        'contact' => ['Contact', 'contact'],
    ];
?>
<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- Resolves every relative URL below against the site root rather than the
     requested path. See peachq_install_path(). -->
<base href="<?= htmlspecialchars(peachq_install_path(), ENT_QUOTES, 'UTF-8') ?>">
<?php if ($description !== ''): ?><meta name="description" content="<?= $description ?>"><?php endif; ?>
<title><?= $title ?></title>
<?php
    // Not on an error page: weberror.php is served for whatever was requested,
    // so the canonical would name a URL that does not exist on peachq.org.
    $peachq_status = http_response_code();
    if ($peachq_status === false || $peachq_status < 400):
?>
<link rel="canonical" href="<?= htmlspecialchars(peachq_canonical_url(), ENT_QUOTES, 'UTF-8') ?>">
<?php endif; ?>
<link rel="icon" href="img/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="16x16" href="img/peachq-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/peachq-32x32.png">
<link rel="apple-touch-icon" sizes="180x180" href="img/peachq-180x180.png">
<link rel="stylesheet" href="css/styles.css">
<script src="mirror-banner.js" defer></script>
<!-- Matomo. Self-hosted at timestored.com/mat, so no third-party analytics
     service sees the traffic. Site 4 is "peachq"; site 1 is TimeStored's own
     site, and pointing this at 1 filed every PeachQ visit under TimeStored.
     Keep in sync with overrides/main.html, which carries the same snippet for
     the MkDocs half of the site; tests/test_pages.sh checks the id matches. -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//www.timestored.com/mat/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '4']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
</head>
<body>
<header class="nav">
  <div class="container nav-inner">
    <a class="brand" href="./"><img class="logo" src="img/peachq-logo.svg" alt="PeachQ logo"><span>Peach<span style="color:var(--peach-strong)">Q</span></span></a>
    <button class="mobile-menu" type="button" data-mobile-menu aria-expanded="false" aria-controls="siteNav">Menu</button>
    <nav class="nav-links" id="siteNav">
<?php foreach ($nav as $key => [$label, $href]): ?>
<?php
      $classes = [];
      if ($active === $key) {
          $classes[] = 'active';
      }
      if ($key === 'repl') {
          $classes[] = 'nav-cta';
      }
      $classAttr = $classes === [] ? '' : ' class="' . htmlspecialchars(implode(' ', $classes), ENT_QUOTES, 'UTF-8') . '"';
?>
      <a href="<?= $href ?>"<?= $classAttr ?>><?= $label ?></a>
<?php endforeach; ?>
      <a href="https://github.com/peachq-org/peachq" target="_blank" rel="noreferrer">GitHub ↗</a>
      <button class="theme-toggle" data-theme-toggle aria-label="Toggle theme"></button>
    </nav>
  </div>
</header>
<div class="preview-ribbon" aria-hidden="true">Early preview</div>

<?php
}

function peachq_page_end(array $scripts = []): void {
?>
<footer class="footer">
  <div class="container footer-inner">
    <div>PeachQ - MIT-licensed open source q, built on Rayforce with DuckDB storage in progress.</div>
    <div><a href="about">Built for the community</a> · <a href="contact">Contact</a> · <a href="https://github.com/peachq-org/peachq">GitHub</a></div>
  </div>
</footer>
<script src="script.js"></script>
<?php foreach ($scripts as $script): ?>
<script src="<?= htmlspecialchars($script, ENT_QUOTES, 'UTF-8') ?>"></script>
<?php endforeach; ?>
</body>
</html>
<?php
}
